### ISSUE TITLE
pg-structure 5.4.0 with ecma6 support?

### ISSUE THREAD

**Issue by rapomon** [ozum/pg-structure#30]
I'm using pg-structure 5.4.0 with ecma6 and don't work, but 4.2.2 works fine, this is my code, I'm doing something wrong?
```
const pgStructure = require('pg-structure');
async function init() {
    let db = await pgStructure(pgConfig, ['public']);
}
init();
```

The error is:

`TypeError: pgStructure is not a function`

Thanks.

**Comment by ozum** [comment]
Could you please try either:

```js
const pgStructure = require('pg-structure').default;
```
 or (with Babel)

```js
import pgStructure from ('pg-structure');
```

Additionally, `await` should be in a function call:

```js
async function() {
  let db = await pgStructure(pgConfig, ['public']);
}
```

or you could use promises:

```
pgStructure(pgConfig, ['public']).then(db => {
  const schemas = db.schemas;
})
```

**Comment by rapomon** [comment]
Thank you!

I have pgStructure inside an async function, I modified the first comment.

Now I tried with:
`const pgStructure = require('pg-structure').default;`

But now the error is:
`[Error: ENOENT: no such file or directory, open 'C:\nodejs\ebm-one\node_modules\pg-structure\module_files\sql\type.sql']`

**Comment by ozum** [comment]
It seems a bug in `pg-structure`. I'm looking it.

**Comment by rapomon** [comment]
Ok, thank you.

I just copied the `module_files` folder to see what happened and I get the following error:

```
error: column not found c.consrc
    at Connection.parseE (C:\nodejs\ebm-one\node_modules\pg\lib\connection.js:604:11)
    at Connection.parseMessage (C:\nodejs\ebm-one\node_modules\pg\lib\connection.js:401:19)
    at Socket.<anonymous> (C:\nodejs\ebm-one\node_modules\pg\lib\connection.js:121:22)

```
I use postgres 12, but version 4.2.2 works fine with this version.

**Comment by ozum** [comment]
I fixed it. Please try latest version.

**Comment by rapomon** [comment]
Ok, now the `module_files` folder exists after install. Thank you!

But I still have the last error commented:

```
error: column not found c.consrc
    at Connection.parseE (C:\nodejs\ebm-one\node_modules\pg\lib\connection.js:604:11)
    at Connection.parseMessage (C:\nodejs\ebm-one\node_modules\pg\lib\connection.js:401:19)
    at Socket.<anonymous> (C:\nodejs\ebm-one\node_modules\pg\lib\connection.js:121:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 261,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'You probably want to refer to column «c.conkey» or «c.conbin».',
  position: '440',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'd:\\pginstaller_12.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c',
  line: '3377',
  routine: 'errorMissingColumn'
}
```

**Comment by rapomon** [comment]
PostgreSQL 12 removes the `pg_constraint.consrc` column. Documentation:

- [PostgreSQL 12](https://www.postgresql.org/docs/12/catalog-pg-constraint.html)
- [PostgreSQL 11](https://www.postgresql.org/docs/11/catalog-pg-constraint.html)

The docs for 11 still include `consrc`, but recommend to use `pg_get_constraintdef`.

**Comment by ozum** [comment]
Yes I realized it in the first message and I'm looking a solution for that now.

**Comment by rapomon** [comment]
Ok, thank you, I moved the problem with the column not found to another issue.

**Comment by ozum** [comment]
Ok, continue on that case.
